import type { Metadata } from "next";
import { Inter } from "next/font/google";
7;
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <Header />
                <div className='main__container p-6'>{children}</div>
                <Footer />
            </body>
        </html>
    );
}
